config/routes.rb
Rails.application.routes.draw do
  resources :challenges, only: %w[index create] do
    member do
      post :upvote
      post :collaborate
    end
  end
  devise_for :employees
  resources :employees, only: :show do
    member do
      get :challenges
      get :collaborations
    end
  end

  root to: 'challenges#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :employee
  belongs_to :tag

  validates :title, :description, presence: true

  has_many :collaborations, dependent: :destroy
  has_many :employees, through: :collaborations
  has_many :votes, dependent: :destroy

  scope :created_by, ->(emp_id) { where(employee_id: emp_id) }

  def self.voted?(challenge_id:, employee_id:)
    Vote.exists?(challenge_id: challenge_id, employee_id: employee_id)
  end

  def self.collaborated?(challenge_id:, employee_id:)
    Collaboration.exists?(challenge_id: challenge_id, employee_id: employee_id)
  end
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :employee
  belongs_to :challenge
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, authentication_keys: [:employee_id]

  validates :employee_id, :password, presence: true

  has_many :collaborations, dependent: :destroy
  has_many :challenges, through: :collaborations
  has_many :votes, through: :challenges
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :challenges, dependent: :destroy

  validates :name, presence: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :challenge
  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_employee!
  before_action :find_challenge, only: %w[upvote collaborate]

  def index
    # get all challenges
    @pagy, @challenges = pagy(Challenge.includes(:tag, :employees), items: 5)

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @challenges, status: :ok }
    end
  end

  def create
    @challenge = ChallengeManager::ChallengeCreator.call(challenge_params, current_employee)

    respond_to do |format|
      if @challenge.save
        challenge_success_response(format, @challenge, :created, msg: 'Challenge was successfully created.')
      else
        challenge_failure_response(format, @challenge, :unprocessable_entity, msg: @challenge.errors.full_messages)
      end
    end
  end

  def upvote
    @upvoted_challenge = ChallengeManager::VoteCreator.call(@challenge, current_employee)

    respond_to do |format|
      unless @upvoted_challenge.errors.any?
        challenge_success_response(format, @challenge, :created, msg: 'Challenge was upvoted successfully' )
      else
        challenge_failure_response(format, @challenge, :forbidden, msg: @upvoted_challenge.errors.full_messages.join(','))
      end
    end
  end

  def collaborate
    @collaborated_challenge = ChallengeManager::CollaborationCreator.call(@challenge, current_employee)

    respond_to do |format|
      unless @collaborated_challenge.errors.any?
        challenge_success_response(format, @challenge, :created, msg: 'Successfully added to the collaborators list')
      else
        challenge_failure_response(format, @challenge, :forbidden, msg: @collaborated_challenge.errors.full_messages.join(','))
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def challenge_params
    params.require(:challenge).permit(:title, :description, :tag_id)
  end

  def find_challenge
    @challenge = Challenge.find(params[:id])
  end

  def challenge_success_response(format, challenge, status, msg:)
    format.html { redirect_back fallback_location: challenges_path, notice: msg }
    format.json { render json: challenge, status: status, location: challenge }
  end

  def challenge_failure_response(format, challenge, status, msg:)
    format.html { redirect_back fallback_location: challenges_path, alert: msg }
    format.json { render json: challenge.errors, status: status, location: challenge }
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee

  def show
  end

  def challenges
    @pagy, @challenges = pagy(Challenge.created_by(@employee).includes(:tag, :employees), items: 5)
  end

  def collaborations
    @pagy, @challenges = pagy(@employee.challenges.includes(:tag, :employees), items: 5)
  end

  private

  def find_employee
    @employee = Employee.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def say_my_name(employee)
    if employee.id == current_employee.id
      return 'My'
    else
      return employee.first_name+"'s"
    end
  end
end

app/views/challenges/_add_challenge.html.erb
<%= form_with model: challenge do |form| %>
  <div class="form-row mt-5 d-flex justify-content-between">
    <div class="form-group col-md-3">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control', required: true %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :description %>
      <%= form.text_field :description, class: 'form-control', required: true %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :tag_id %>
      <%= form.collection_select :tag_id, Tag.order(:name), :id, :name, {}, {class: 'form-control'} %>
    </div>
    <div class="form-group">
      <%= form.label :add%>
      <%= form.submit class: 'btn btn-primary form-control '%>
    </div>
  </div>
<% end %>

app/views/challenges/_challenge.html.erb
<tr>
  <th scope="row"><%= challenge.id %></th>
  <td><%= challenge.title %></td>
  <td class="text-break"><%= challenge.description %></td>
  <td><%= challenge.votes.count %></td>
  <td><%= link_to challenge.employee.first_name, employee_path(challenge.employee) %></td>
  <td><%= challenge.created_at.to_date.inspect %></td>
  <td><%= challenge.tag.name %></td>
  <td class="text-break"><%= challenge.employees.map { |employee| link_to employee.first_name, employee_path(employee) }.join(', ').html_safe %></td>
  <td class="d-flex justify-content-around">
    <%= button_to 'upvote', upvote_challenge_path(challenge), class: 'btn btn-primary' %>
    <%= button_to 'collaborate', collaborate_challenge_path(challenge), class: 'btn btn-secondary' %>
  </td>
</tr>

app/views/challenges/_challenge_table.html.erb
<div class="table-responsive">
  <table class="table table-striped" id="challenge-table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Title</th>
        <th scope="col" data-sorter="false">Description</th>
        <th scope="col">Votes</th>
        <th scope="col">Created_by</th>
        <th scope="col">Create_date</th>
        <th scope="col">Tags</th>
        <th scope="col">Collaborators</th>
        <th scope="col" class="text-center" data-sorter="false">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @challenges.each do |challenge| %>
        <%= render 'challenges/challenge', challenge: challenge %>
      <% end %>
    </tbody>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/challenges/_form.html.erb
<%= form_with model: Challenge.new do |form| %>
  <div class="form-row mt-5 d-flex justify-content-between">
    <div class="form-group col-md-3">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control', required: true %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :description %>
      <%= form.text_field :description, class: 'form-control', required: true %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :tag_id %>
      <%= form.collection_select :tag_id, Tag.order(:name), :id, :name, {}, {class: 'form-control'} %>
    </div>
    <div class="form-group">
      <%= form.label :action%>
      <%= form.submit class: 'btn btn-primary form-control '%>
    </div>
  </div>
<% end %>

app/views/challenges/index.html.erb
<div class="w-75 mx-auto">
  <%= render 'form', object: @challenge %>
  <h1 class="text-center mb-4">Challenges List</h1>
  <%= render 'challenge_table' %>
</div>

app/views/employees/challenges.html.erb
<div class="w-75 mx-auto">
  <h1 class="text-center m-4"><%= say_my_name(@employee) %> Challenges</h1>
  <%= render 'challenges/challenge_table' %>
  <%= link_to "Back", :back %>
</div>

app/views/employees/collaborations.html.erb
<div class="w-75 mx-auto">
  <h1 class="text-center m-4"><%= say_my_name(@employee) %> Collaborations</h1>
  <%= render 'challenges/challenge_table' %>
  <%= link_to "Back", :back %>
</div>

app/views/employees/show.html.erb
<div class="w-75 mx-auto">
  <h1><%= @employee.employee_id %></h1>
  <h1><%= @employee.first_name + ' ' + @employee.last_name %></h1>
  <h1><%= @employee.email %></h1>
  <%= link_to "Challenges", challenges_employee_path(@employee) %>
  <%= link_to "Collaborations", collaborations_employee_path(@employee) %>
  <%= link_to "Back", root_path %>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |type, msg| %>
    <% if type == "notice" %>
      <div class="alert alert-success alert-dismissible fade show">
    <% elsif type == "alert" %>
      <div class="alert alert-danger alert-dismissible fade show">
    <% else %>
      <div class='alert alert-<%= "#{type}" %> alert-dismissible fade show'>
    <% end %>
    <a href="#" class="close" data-dismiss="alert">&times;</a>
    <ul>
      <li>
        <%= msg %>
      </li>
    </ul>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary">
  <%= link_to 'Hackathon', root_path, class: 'navbar-brand' %>
  <% if employee_signed_in? %>
    <div class="dropdown">
      <button class="btn btn-warning dropdown-toggle font-weight-bold" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_employee.first_name + ' ' + current_employee.last_name%>
      </button>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to 'My Challenges', challenges_employee_path(current_employee), class: 'dropdown-item' %>
        <%= link_to 'My Collaborations', collaborations_employee_path(current_employee), class: 'dropdown-item' %>
        <%= link_to 'My Profile', employee_path(current_employee), class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
        <%= link_to "Logout '#{current_employee.first_name}'", destroy_employee_session_path, class: 'dropdown-item text-danger font-weight-bold', method: :delete %>
      </div>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackathon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!-- As a link -->
<nav class="navbar navbar-dark bg-primary">
  <%= link_to 'Hackathon', challenges_path, class: 'navbar-brand' %>
  <% if employee_signed_in? %>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Logout '#{current_employee.employee_id}'", destroy_employee_session_path, class: 'nav-link', method: :delete %>
      </li>
    </ul>
  <% end %>
</nav>